// You can save this in a new file: src/api/mockData.js

export const productsByCategory = {
  "Produce": [
    { id: 1, name: "Apple", cost: 180, url: "src/assets/produce/apple.png" },
    { id: 2, name: "Banana", cost: 60, url: "src/assets/produce/banana.jpg" },
    { id: 3, name: "Carrot", cost: 50, url: "src/assets/produce/carrot.png" },
    { id: 4, name: "Broccoli", cost: 75, url: "src/assets/produce/boo.png" },
    { id: 5, name: "Spinach (Palak)", cost: 25, url: "src/assets/produce/spinach.png" },
    { id: 6, name: "Potato", cost: 40, url: "src/assets/produce/potato.png" },
    { id: 7, name: "Onion", cost: 35, url: "src/assets/produce/onion.png" },
    { id: 8, name: "Tomato - Hybrid", cost: 30, url: "src/assets/produce/tomato.png" },
    { id: 9, name: "Grapes - Green", cost: 90, url: "src/assets/produce/grapes.png" },
    { id: 10, name: "Cucumber", cost: 20, url: "src/assets/produce/cucumber.png" },
    { id: 11, name: "Bell Pepper (Capsicum)", cost: 55, url: "src/assets/produce/bell-pepper.png" },
    { id: 12, name: "Lettuce - Iceberg", cost: 80, url: "src/assets/produce/lettuce.png" }
  ],
  "Dairy & Eggs": [
    { id: 13, name: "Amul Gold Milk", cost: 66, url: "src/assets/dairy/amul.png" },
    { id: 14, name: "Amul Butter", cost: 52, url: "src/assets/dairy/butter.png" },
    { id: 15, name: "Nestle a+ Curd", cost: 45, url: "src/assets/dairy/curd.png" },
    { id: 16, name: "ID Fresh Paneer", cost: 95, url: "src/assets/dairy/panner.png" },
    { id: 17, name: "Britannia Cheese Slices", cost: 120, url: "src/assets/dairy/cheese.png" },
    { id: 18, name: "Farm Fresh White Eggs", cost: 72, url: "src/assets/dairy/eggs.png" },
    { id: 19, name: "Amul Ghee", cost: 550, url: "src/assets/dairy/ghee.png" },
    { id: 20, name: "Epigamia Greek Yogurt", cost: 85, url: "src/assets/dairy/yogurt.png" },
    { id: 21, name: "Paper Boat Buttermilk", cost: 25, url: "src/assets/dairy/buttermilk.png" },
    { id: 22, name: "Amul Kool Lassi", cost: 20, url: "src/assets/dairy/lassi.png" },
    { id: 23, name: "Amul Fresh Cream", cost: 68, url: "src/assets/dairy/cream.png" }
  ],
  "Deli & Prepared Foods": [
    { id: 24, name: "Chicken Salami Slices", cost: 150, url: "src/assets/deli/chicken.png" },
    { id: 25, name: "Ready-to-Eat Chicken Biryani", cost: 250, url: "src/assets/deli/ready.png" },
    { id: 27, name: "Vegetable Spring Rolls (6 pcs)", cost: 120, url: "src/assets/deli/spring.png" },
    { id: 28, name: "Paneer Tikka Skewers", cost: 200, url: "src/assets/deli/pp.png" },
    { id: 29, name: "Coleslaw Salad", cost: 90, url: "src/assets/deli/coleslaw.png" },
    { id: 30, name: "Garlic Bread Loaf", cost: 70, url: "src/assets/deli/garlic-bread.png" },
    { id: 31, name: "Frozen Samosas (10 pcs)", cost: 110, url: "src/assets/deli/samosa.png" },
    { id: 32, name: "Pasta Salad", cost: 130, url: "src/assets/deli/pasta-salad.png" },
    { id: 33, name: "Veg Sandwich", cost: 80, url: "src/assets/deli/sandwich.png" },
    { id: 34, name: "Chicken Nuggets", cost: 220, url: "src/assets/deli/nuggets.png" }
  ],
  "Beverages": [
    { id: 35, name: "Tropicana Orange Juice", cost: 125, url: "src/assets/beverages/juice.png" },
    { id: 36, name: "Coca-Cola (1.25L)", cost: 80, url: "src/assets/beverages/coco.png" },
    { id: 37, name: "Kinley Mineral Water (1L)", cost: 20, url: "src/assets/beverages/kinley.png" },
    { id: 38, name: "Red Label Tea (500g)", cost: 250, url: "src/assets/beverages/red.png" },
    { id: 39, name: "Bru Instant Coffee", cost: 280, url: "/assets/beverages/coffee.png" },
    { id: 40, name: "Red Bull Energy Drink", cost: 125, url: "/assets/beverages/red-bull.png" },
    { id: 41, name: "Real Mixed Fruit Juice", cost: 110, url: "/assets/beverages/mixed-juice.png" },
    { id: 42, name: "Gatorade Sports Drink", cost: 50, url: "/assets/beverages/gatorade.png" },
    { id: 43, name: "Lipton Green Tea (25 bags)", cost: 160, url: "/assets/beverages/green-tea.png" },
    { id: 44, name: "Appy Fizz", cost: 40, url: "/assets/beverages/appy-fizz.png" },
    { id: 45, name: "Bournvita Health Drink", cost: 220, url: "/assets/beverages/bournvita.png" }
  ],
  "Meat & Seafood": [
    { id: 46, name: "Chicken Breast - Boneless", cost: 250, url: "src/assets/meat/brest.png" },
    { id: 47, name: "Mutton Curry Cut", cost: 700, url: "src/assets/meat/mutton.png" },
    { id: 48, name: "Rohu Fish - Steaks", cost: 350, url: "src/assets/meat/fish.png" },
    { id: 49, name: "Prawns - Cleaned", cost: 450, url: "src/assets/meat/praws.png" },
    { id: 50, name: "Chicken Drumsticks", cost: 220, url: "src/assets/meat/drumsticks.png" },
    { id: 51, name: "Ground Lamb (Keema)", cost: 750, url: "/assets/meat/keema.png" },
    { id: 52, name: "Basa Fish Fillet", cost: 400, url: "/assets/meat/basa.png" },
    { id: 53, name: "Chicken Lollipops", cost: 280, url: "/assets/meat/lollipops.png" },
    { id: 54, name: "Sardines", cost: 150, url: "/assets/meat/sardines.png" },
    { id: 55, name: "Bacon Strips", cost: 350, url: "/assets/meat/bacon.png" },
    { id: 56, name: "Chicken Sausages", cost: 180, url: "/assets/meat/sausages.png" }
  ],
  "Snacks & Candy": [
    { id: 57, name: "Lays Classic Salted Chips", cost: 20, url: "src/assets/snacks/lays.png" },
    { id: 58, name: "Britannia Good Day Cookies", cost: 40, url: "src/assets/snacks/cook.png" },
    { id: 59, name: "Cadbury Dairy Milk Silk", cost: 80, url: "src/assets/snacks/card.png" },
    { id: 60, name: "Haldiram's Aloo Bhujia", cost: 55, url: "src/assets/snacks/aab.png" },
    { id: 61, name: "Kurkure Masala Munch", cost: 20, url: "/assets/snacks/kurkure.png" },
    { id: 62, name: "Parle-G Biscuits", cost: 10, url: "/assets/snacks/parle-g.png" },
    { id: 63, name: "Act II Popcorn", cost: 30, url: "/assets/snacks/popcorn.png" },
    { id: 64, name: "Bingo Mad Angles", cost: 20, url: "/assets/snacks/mad-angles.png" },
    { id: 65, name: "Roasted Cashews", cost: 250, url: "/assets/snacks/cashews.png" },
    { id: 66, name: "Oreo Biscuits", cost: 30, url: "/assets/snacks/oreo.png" },
    { id: 67, name: "Nestle KitKat", cost: 25, url: "/assets/snacks/kitkat.png" },
    { id: 68, name: "Too Yumm! Karare", cost: 20, url: "/assets/snacks/too-yumm.png" }
  ],
  "Frozen": [
    { id: 69, name: "Safal Frozen Peas", cost: 50, url: "src/assets/frozen/safal.png" },
    { id: 70, name: "McCain French Fries", cost: 99, url: "src/assets/frozen/french.png" },
    { id: 71, name: "Amul Vanilla Ice Cream", cost: 150, url: "src/assets/frozen/amulice.png" },
    { id: 72, name: "Mother Dairy Frozen Corn", cost: 45, url: "src/assets/frozen/corn.png" },
    { id: 73, name: "Kwality Wall's Cornetto", cost: 40, url: "src/assets/frozen/cornetto.png" },
    { id: 74, "name": "ID Malabar Parota", "cost": 85, "url": "/assets/frozen/parota.png" },
    { id: 75, "name": "Chicago Pizza - Veggie", "cost": 299, "url": "/assets/frozen/pizza.png" },
    { id: 76, "name": "Venkys Chicken Momos", "cost": 180, "url": "/assets/frozen/momos.png" },
    { id: 77, "name": "Gits Ready-to-Eat Dal Makhani", "cost": 115, "url": "/assets/frozen/dal-makhani.png" },
    { id: 78, "name": "Sumeru Veggie Burger Patty", "cost": 140, "url": "/assets/frozen/burger-patty.png" },
    { id: 79, "name": "Baskin Robbins Pralines 'n Cream", "cost": 350, "url": "/assets/frozen/baskin-robbins.png" }
  ],
  "Bakery": [
    { id: 80, name: "Britannia Brown Bread", cost: 45, url: "src/assets/bakery/bread.png" },
    { id: 81, name: "Pillsbury Croissants", cost: 120, url: "src/assets/bakery/pully.png" },
    { id: 82, name: "Chocolate Chip Muffins (4 pcs)", cost: 150, url: "src/assets/bakery/chip.png" },
    { id: 83, name: "Local Bakery White Bread", cost: 40, url: "src/assets/bakery/white.png" },
    { id: 84, name: "Fruit Cake Slice", cost: 60, url: "/assets/bakery/fruit-cake.png" },
    { id: 85, name: "English Oven Burger Buns", cost: 35, url: "/assets/bakery/burger-buns.png" },
    { id: 86, name: "Britannia Rusk Toast", cost: 50, url: "/assets/bakery/rusk.png" },
    { id: 87, name: "Donuts (Assorted)", cost: 180, url: "/assets/bakery/donuts.png" },
    { id: 88, name: "Theobroma Chocolate Brownie", cost: 95, url: "/assets/bakery/brownie.png" },
    { id: 89, name: "Garlic & Herb Breadsticks", cost: 90, url: "/assets/bakery/breadsticks.png" },
    { id: 90, name: "Lamington Cake", cost: 250, url: "/assets/bakery/lamington.png" }
  ],
  "Dry Goods & Pasta": [
    { id: 91, name: "Daawat Basmati Rice (1kg)", cost: 140, url: "src/assets/dry-goods/daawat.png" },
    { id: 92, name: "Aashirvaad Atta (5kg)", cost: 280, url: "src/assets/dry-goods/ashirvad.png" },
    { id: 93, name: "Tata Sampann Toor Dal", cost: 160, url: "src/assets/dry-goods/gg.png" },
    { id: 94, name: "Disano Penne Pasta", cost: 99, url: "src/assets/dry-goods/pasta.png" },
    { id: 95, name: "Saffola Masala Oats", cost: 185, url: "src/assets/dry-goods/oats.png" },
    { id: 96, name: "Organic Tattva Quinoa", cost: 250, url: "src/assets/dry-goods/quinoa.png" },
    { id: 97, name: "24 Mantra Organic Besan", cost: 80, url: "/assets/dry-goods/besan.png" },
    { id: 98, name: "Rajma Chitra", cost: 130, url: "/assets/dry-goods/rajma.png" },
    { id: 99, name: "Kabuli Chana (Chickpeas)", cost: 120, url: "/assets/dry-goods/chana.png" },
    { id: 100, name: "Poha (Flattened Rice)", cost: 50, url: "/assets/dry-goods/poha.png" },
    { id: 101, name: "Fortune Sun Lite Oil", cost: 150, url: "/assets/dry-goods/oil.png" }
  ],
  "Condiments & Sauces": [
    { id: 102, name: "Kissan Tomato Ketchup", cost: 115, url: "src/assets/condiments/ketchup.png" },
    { id: 103, name: "Veeba Mayonnaise", cost: 90, url: "src/assets/condiments/veeba.png" },
    { id: 104, name: "Ching's Secret Soy Sauce", cost: 60, url: "src/assets/condiments/soy.png" },
    { id: 105, name: "Patanjali Honey", cost: 220, url: "src/assets/condiments/honey.png" },
    { id: 106, name: "Mother's Recipe Mixed Pickle", cost: 130, url: "src/assets/condiments/pickle.png" },
    { id: 107, name: "FunFoods Peanut Butter", cost: 190, url: "src/assets/condiments/peanut-butter.png" },
    { id: 108, name: "Maggi Hot & Sweet Sauce", cost: 105, url: "src/assets/condiments/hot-sweet-sauce.png" },
    { id: 109, name: "Del Monte Pasta Sauce", cost: 150, url: "/assets/condiments/pasta-sauce.png" },
    { id: 110, name: "American Garden Mustard", cost: 140, url: "/assets/condiments/mustard.png" },
    { id: 111, name: "Tabasco Hot Sauce", cost: 200, url: "/assets/condiments/tabasco.png" },
    { id: 112, name: "Kissan Mixed Fruit Jam", cost: 165, url: "/assets/condiments/jam.png" }
  ],
  "Canned Goods & Soups": [
    { id: 113, name: "Del Monte Canned Corn", cost: 70, url: "src/assets/canned/ssh.png" },
    { id: 114, name: "Heinz Baked Beans", cost: 180, url: "src/assets/canned/abc.png" },
    { id: 115, name: "Knorr Tomato Soup", cost: 60, url: "src/assets/canned/soup.png" },
    { id: 116, name: "Golden Crown Pineapple Slices", cost: 95, url: "src/assets/canned/pine.png" },
    { id: 117, name: "Century Tuna Flakes", cost: 210, url: "src/assets/canned/tuna.png" },
    { id: 118, name: "Maggi Hot Cup Noodles", cost: 50, url: "src/assets/canned/noodles.png" },
    { id: 119, name: "Batchelors Cup a Soup", cost: 25, url: "src/assets/canned/cup-a-soup.png" },
    { id: 120, name: "Amulya Dairy Whitener", cost: 240, url: "/assets/canned/dairy-whitener.png" },
    { id: 121, name: "Canned Mushrooms", cost: 110, url: "/assets/canned/mushrooms.png" },
    { id: 122, name: "Nestle Milkmaid", cost: 135, url: "/assets/canned/milkmaid.png" },
    { id: 123, name: "Knorr Manchow Soup", cost: 60, url: "/assets/canned/manchow-soup.png" }
  ],
  "Breakfast": [
    { id: 124, name: "Kellogg's Corn Flakes", cost: 190, url: "src/assets/breakfast/oats.png" },
    { id: 125, name: "Quaker Oats", cost: 175, url: "src/assets/breakfast/Oaats.png" },
    { id: 126, name: "Bagrry's Muesli", cost: 280, url: "src/assets/breakfast/nuts.png" },
    { id: 127, name: "ID Fresho Idli & Dosa Batter", cost: 75, url: "src/assets/breakfast/idly.png" },
    { id: 128, name: "i-D Instant Filter Coffee Decoction", cost: 90, url: "src/assets/breakfast/coffee-decoction.png" },
    { id: 129, name: "Hershey's Chocolate Syrup", cost: 200, url: "src/assets/breakfast/choco-syrup.png" },
    { id: 130, name: "MTR Poha Mix", cost: 65, url: "src/assets/breakfast/poha-mix.png" },
    { id: 131, name: "Pillsbury Pancake Mix", cost: 150, url: "/assets/breakfast/pancake-mix.png" },
    { id: 132, name: "Nutella Spread", cost: 370, url: "/assets/breakfast/nutella.png" },
    { id: 133, name: "Tata Salt Lite", cost: 40, url: "/assets/breakfast/salt.png" },
    { id: 134, name: "Madhur Sugar", cost: 55, url: "/assets/breakfast/sugar.png" }
  ]
};